### ISSUE TITLE
Advanced search using structure not limiting with  Find compounds which contain this structure 

### ISSUE THREAD

**Issue by cerivs** [ebi-chebi/ChEBI#3471]
When I put in any structure and limit with the choice to " Find compounds which contain this structure" using the advanced search I get the maximum possible number of compounds and they don't contain the structure I am using to search.  This is making it extremely difficult to find entities in ChEBI.

**Comment by muthuvenkat** [comment]
Thanks for reporting. Its fixed now.

**Comment by ANiknejad** [comment]
hello @muthuvenkat @amalik01 

I would like to reopen this issue, because as far as I see, the problem is back!

**Comment by amalik01** [comment]
Hi @ANiknejad 
Can you send over some examples of where the structure search fails. Thanks

**Comment by ANiknejad** [comment]
@amalik01 
https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:17120

and click on [Find compounds which contain this structure]

https://www.ebi.ac.uk/chebi/advancedSearchFT.do;jsessionid=D5421AC5DFB33CC2EE7C72AD872F0869?chebiId=17120&structureSearchMethod=substructure

**Comment by ANiknejad** [comment]
https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:27689
[
](https://www.ebi.ac.uk/chebi/advancedSearchFT.do;jsessionid=A08A7484CE1F950BA94E1FC0A62B416D?chebiId=27689&structureSearchMethod=substructure)

12927 results, among them (page 6)
https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:82825

**Comment by amalik01** [comment]
Thanks @ANiknejad for bringing this to our attention. Unfortunately, we do not have the resources to fix this issue in the current ChEBI since the main focus of our current work is the redevelopment of ChEBI. This particular issue has already been fixed in the new version that we are developing (we have moved away from Orchem to RDKit for structure searches). You will be able to see the changes once the beta version is out (hopefully before the end of the year).

**Comment by ANiknejad** [comment]
thank you, Adnan, for clear explanations
